# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# You can find config options at: https://jekyllrb.com/docs/configuration/options/
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# theme                  : "zer0-mistakes-jekyll"
# remote_theme           : "bamr87/zer0-mistakes"
theme_skin                : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings

title                    : "IT-Journey"
subtitle                 : "Git it done" # site tagline that appears below site title in masthead
subtitle_url             : "127.0.0.1"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
title_separator          : "|"
locale                   : "en-US"
name                     : &name "Amr Abdel"
email                    : amr.abdel@gmail.com
description              : &description >- # this means to ignore newlines until "baseurl:"
  "Scrolls and spells of IT magic."
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl                  : # the subpath of your site, e.g. "/blog"
url                      : "https://bamr87.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "bamr87/bamr87.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
local_repo               : "bamr87.github.io"
local_git_pc             : "C:/Users/AmrAbdel-Motaleb/OneDrive/Documents/GitHub/"
local_git_mac            : "/Users/amr-mb/github"
teaser                   : /assets/images/teaser_default-500x300.png # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/images/great-lamda-pyramids-v1.png # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
port                     : 4001 # Jekyll Serve Dev port
dg_port                  : "4002" # Doppelganger site

# Identity

author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/amr-avatar.jpg"
  bio              : "IT nerd trying to be an IT hero"
  location         : "Denver, CO"
  links:
    - label: "BASH Consulting"
      icon: "fas fa-fw fa-link"
      url: "https://bashconsultants.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bamr87"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bamr87"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bamrman"

# Social Sharing
twitter:
  username               : &twitter "amr"
facebook:
  username               : &facebook "amr"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/B_Logo_v2_0.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links                  : # An array of links to social media profiles
    - "https://twitter.com/bamr87"
    - "https://www.facebook.com/bamrabdel"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# include:
#   - _docs/
#   - _cheats/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Footer Links Settings

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bamr87"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bamr87"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/bamr87"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  cheats:
    output: true
    permalink: /:collection/:path/

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # ALL
  - scope:
      path: ""
    values:
      layout: single
      show_date: true
      author_profile: false
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true
      toc_sticky: true     
      sidebar:
        - nav: home
      # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      toc: true
      toc_sticky: true      
  # _docs
  - scope:
      path: "_docs"
      type: docs
    values:
      layout: single
      share: true
      toc: true
      author_profile: false
      sidebar:
        - nav: docs
  # _cheats
  - scope:
      path: "_cheats"
      type: cheats
    values:
      layout: single
      share: true
      toc: true
      author_profile: false
      toc_sticky: true
      sidebar:
        - nav: cheat

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


